# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest python3-twine
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        echo Add your testing here
        pytest -v
    - name: publish package with twine
      run: |
        # twine register dist/viki-pkg-1.0.0.tar.gz -r viki-pkg
        twine upload --verbose --config-file .viki_pipirc --repository local /dist/* 
        # twine upload --repository-url https://otomato.jfrog.io/artifactory/api/pypi/PyPi --username candidate --password AP3dLQtysxAU27HAhoJAzUiGfYJ 
