# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout step
      uses: actions/checkout@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
<<<<<<< HEAD
<<<<<<< HEAD
        pytest -v
    - name: Build and publish
      run: |
        python setup.py sdist
<<<<<<< HEAD
        twine upload -u ${{ secrets.PYPI_API_USER }} -p ${{ secrets.PYPI_API_TOKEN }} --repository-url https://otomato.jfrog.io/artifactory/api/pypi/PyPi dist/*
    
=======
    - name: upload with Twine
      run: |
        twine upload --config-file .pypirc dist/*
>>>>>>> 5f228c9... fixing typo in steps
=======
        pytest -rp
    - name: Publish the egg
      run: |
        cp .pypirc $HOME/
        python3 setup.py sdist upload -r local
>>>>>>> 188172a... init2
=======
        pytest -v
    - name: Build and publish
      run: |
        python setup.py sdist
        twine upload -u ${{ secrets.PYPI_API_USER }} -p ${{ secrets.PYPI_API_TOKEN }} --repository-url https://otomato.jfrog.io/artifactory/api/pypi/PyPi dist/*
    
>>>>>>> 565ca6c... hiding secrets & removed .pypirc
